### ISSUE TITLE
Debes optimizarlo

### ISSUE THREAD

**Issue by whitehatdevv** [iBigBitDev97/ejercicios-arrays-29-10#1]
https://github.com/iBigBitDev97/ejercicios-arrays-29-10/blob/aeb5d2c4496a7abeb5a153d948289f723f0438ad/assert/resources/scripts/index.js#L15

Tienes que crear una única función que este parametrizada para que no haya dos bubble sort solo uno. Lo más importante es que haya una sola función con un parámetro llamado `type` que sea '>' '<' y actuar de una manera u otra.

Debes comentar el código de manera superficial y profesional. No comentes de manera evidente!!

**Comment by iBigBitDev97** [comment]
Optimizado
